### ISSUE TITLE
[HOS-13] Login 

### ISSUE THREAD

**Issue by GuilhermeAGouveia** [celso-patiri/hostel-app-gcva#18]
## Descrição

Como gerente de reservas
Quero logar no hostelApp
para criar reservas para novos hóspedes e visualizar
uma lista com todos os hóspedes que já se hospedaram no hostel.

## Critérios de aceitação
- [x] Um login tem um nome de usuário e uma senha.
- [ ] Deve haver uma opção explícita para lembrar as credenciais do gerente de reservas.
- [ ] Uma mensagem de login incorreta deve ser mostrada para
usuário e/ou senha.
- [ ] A senha deve ter pelo menos 8 caracteres.

## Tasks

[Frontend]

- [ ] Adicionar campos de entrada de texto: Username e Password;
- [ ] Adicionar um botão de "Login";
- [ ] Entrada de texto Password deve permitir ocultar e exibir a senha;
- [ ] Em caso de erro no Login, mostrar um banner indicando erro para o usuário;
- [ ] Em caso de sucesso, redirecioná-lo para a Home Page;

[Backend] 

- [x] Verificar a partir da API de Security a autenticação do Usuário;
- [x] Criar um controlador para o "Login";
