### ISSUE TITLE
[HOS-14]  Home page

### ISSUE THREAD

**Issue by RafaelBittar** [celso-patiri/hostel-app-gcva#19]
## Descrição

Como um visitante do site, eu quero ser capaz de visualizar o que preciso saber em relação ao Hostel Sparkling Water para que possa ponderar sobre a contratação dos serviços oferecidos por ele.

## Critérios de aceitação
- [ ] A página inicial do site deve mostrar as informações principais referentes ao Hostel;
- [ ] Na página inicial deve ser possível acessar links referentes aos outros ambientes do site (lista de hóspedes, serviço de reservas, login e logout);
- [ ] A página inicial do site deve mostrar uma breve história do Hostel;
- [ ] A página inicial do site deve mostrar informações de contato com o Hostel;
- [ ] A página inicial do site deve mostrar informações de localização e como chegar ao Hostel.

## Tasks
[Frontend]
- [ ] Criar botões de ação; [ Login ] e [ Logout ]
- [ ] Adicionar o Header 
- [ ] Adicionar o Footer;
- [ ] Adicionar um botão para acessar a listagem de Clientes;

[Backend]
