### ISSUE TITLE
[HOS-17] Logout

### ISSUE THREAD

**Issue by Joaovitron999** [celso-patiri/hostel-app-gcva#20]
## Descrição

Como usuário
Quero deslogar no hostelApp
para encerrar a minha sessão no sistema

## Critérios de aceitação
- [ ] Uma opção para logout deve estar disponível
- [ ] O usuário logado deve ser deslogado da aplicação

## Task
[Frontend]

- [ ] Criar um component button que tenha como ação o logout e esteja disponível para uso em qualquer página, desde que o usuário esteja logado
- [ ] Ação do button: Com um cliente HTTP do JS (axios, XMLHttpRequest) que faça uma requisição de logout no backend

[Backend]

- [ ] Criar um controlador para logout
