### ISSUE TITLE
[HOS-16] Filtrar clientes

### ISSUE THREAD

**Issue by GuilhermeAGouveia** [celso-patiri/hostel-app-gcva#21]
## Descrição

Como gerente de reservas
Quero filtrar a lista de clientes no hostelApp
para facilitar a localizações dos dados desejados em determinada consulta

## Critérios de aceitação
- [x] O filtro deve funcionar ao menos pelo nome
- [x] A resposta do filtro deve ser rápida, cerca de 5 segundos no máximo
- [x] O nome pode conter a substring digitada na entra ne texto para filtro, não precisando ser um match perfeito

## Task

[Frontend]

- [x] Adicionar uma função que aplica Regex em cada item dos vetores que representam os Clientes;
- [x] Adicionar uma entrada de texto do Filtro;
- [x] Adicionar o botão de "Filtro";
- [x] Adicionar o botão "Limpar" referente ao Filtro.

[Backend]

- [x] Criar controlador que suporte a filtragem de hospedes
