### ISSUE TITLE
[HOS-15] Cadastrar novo hóspede

### ISSUE THREAD

**Issue by RafaelBittar** [celso-patiri/hostel-app-gcva#22]
Eu como gerente de reservas, quero ser capaz de cadastrar um novo hóspede para que possa manter um registro atualizado de quem se já se hospedou no hostel Sparkling Water.

- [ ] Um hóspede possui os seguintes campos: primeiro nome, último nome, email, telefone, endereço, estado e país;
- [ ] Além de telefone, todos os campos de hóspede são obrigatórios;
- [ ] O gerente de reservas deve ser notificado caso tenha preenchido um campo com informações inválidas;
- [ ] O gerente de reservas deve ser informado caso tente inserir um hóspede que já está cadastrado.

## Tasks

[Frontend]

- [x] Adicionar um Header e Footer;
- [x] Adicionar os campos de entrada de texto: "Firstname", "Lastname", "E-mail", "Phonenumber", "Address", "Country", "State".
- [x] Adicionar o botão "Submit";
- [x] Adicionar o botão "Return" para a lista de Hóspedes;
- [x] Adicionar uma função para definir obrigatoriedade dos campos de Hóspede.

[Backend] 

- [x] Criar o controlador para cadastrar Hóspedes
