### ISSUE TITLE
[HOS-18] Exibir lista de hóspedes

### ISSUE THREAD

**Issue by RafaelBittar** [celso-patiri/hostel-app-gcva#23]
## Descrição
Eu como um gerente de reservas, quero ser capaz de exibir uma lista de todos os hóspedes já cadastrados no sistema do Hostel

## Critérios de aceitação
- [x] A lista deve ser exibida permitindo diferentes tipos de ordenação (por nome, sobrenome, e-mail, etc.);
- [x] Deve ser possível realizar uma busca para encontrar hóspedes específicos por nome e sobrenome.

## Tasks

[Frontend]

- [x] Adicionar uma lista do tipo "table" que contenha todos os Hóspedes como itens;
- [x] Adicionar um botão "Novo Hóspede";
- [x] Em cada item da lista de Hóspedes exibir um botão que altere seu status entre 'ativo' e 'inativo'.
- [x] Consumir dados fornecidos pelo backend
- [x] Definir os elementos para suporte à Paginação

[Backend] 

- [x] Criar um controlador que faça o acesso no Modelo que retorne a lista de Clientes usando um esquema de paginação;
- [x] Retornar informações ordenadas por telefone (default);
