### ISSUE TITLE
[HOS-1] Definir tecnologias FRONT-END

### ISSUE THREAD

**Issue by caioreius** [celso-patiri/hostel-app-gcva#5]
## Descrição

Eu como Desenvolvedor, quero definir em conjunto com o time as tecnologias a serem utilizadas para realizar a parte de front-end do projeto Hostel Sparkling Water.

## Tasks

- [x] Permitir o reuso baseado na construção de componentes;
- [x] Ampla comunidade de desenvolvedores em caso de dúvidas;
- [x] Uma requisição RESTful tem que ocorrer em no máximo: 0.X segundos;
- [x] Implementar um teste Hello World para verificar o funcionamento e atualizá-lo no repositório do GitHub;

## Quem completou:

- [ ] Caio
- [ ] Guilherme
- [ ] Celso
- [ ] João
- [ ] Arthur
- [ ] Rafael
- [ ] André
- [ ] Gabriel

**Comment by GuilhermeAGouveia** [comment]
Escolhido: HTML/CSS/JS
