### ISSUE TITLE
[HOS-2] Configurar Repositório do GitHub

### ISSUE THREAD

**Issue by GuilhermeAGouveia** [celso-patiri/hostel-app-gcva#7]
## Descrição

Eu como Membro do time Scrum, quero criar um repositório na plataforma GitHub e nele incluir o restante do time de desenvolvimento com a função de colaboradores.

## Tasks
- [x] Criar Repositório no GitHub;
- [x] Convidar todos os membros do grupo como colaboradores;
- [x] Definir arquivo .gitignore inicial;
- [x] Definir a licença;
- [x] Todos os membros do time de desenvolvimento devem criar um PAT para acessar os repositórios;

## Quem completou:

- [x] Caio
- [x] Guilherme
- [x] Celso
- [x] João
- [x] Arthur
- [x] Rafael
- [x] André
- [x] Gabriel
