### ISSUE TITLE
[HOS-5] Definir e configurar banco de dados

### ISSUE THREAD

**Issue by caioreius** [celso-patiri/hostel-app-gcva#8]
## Descrição

Eu como Desenvolvedor, quero escolher um Sistema Gerenciador de Banco de Dados para implementar a persistência de dados da aplicação Hostel Sparkling Water.

## Tasks

- [x] Decidir com o grupo qual será o banco de dados utilizado;
- [x] Todos os membros do grupo devem baixar o banco de dados e configurar um usuário;
- [x] Rodar o script para criação da tabela Hospede e popular o banco com os 23 hóspedes;

## Quem completou

- [x] Caio
- [x] Guilherme
- [x] Celso
- [x] João
- [x] Arthur
- [x] Rafael
- [x] André
- [x] Gabriel

**Comment by GuilhermeAGouveia** [comment]
SGBD escolhido: MySQL
