### ISSUE TITLE
[HOS-9] Estudar funcionamento de APIs

### ISSUE THREAD

**Issue by caioreius** [celso-patiri/hostel-app-gcva#9]
## Descrição

Eu como Desenvolvedor, quero entender sobre como consumir dados de uma API, para que eu possa trabalhar com os dados persistidos no banco de dados dentro de uma View.

## Tasks
- [ ] Entender sobre JSON;
- [ ] Entender Asyncronous function ou Promises (JS);
- [ ] Entender sobre HTTP methods rest.

## Quem completou:

- [ ] Caio
- [x] Guilherme
- [ ] Celso
- [ ] João
- [ ] Arthur
- [ ] Rafael
- [ ] André
- [ ] Gabriel
